# Generated by Django 2.2.12 on 2020-05-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='published_date',
        ),
    ]
