# Generated by Django 2.2.12 on 2020-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_practice_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='state',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
