# Generated by Django 2.2.12 on 2020-05-31 22:17

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_practice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='state_select',
            field=localflavor.us.models.USStateField(default='null', max_length=2),
            preserve_default=False,
        ),
    ]
