# Generated by Django 2.2.12 on 2020-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_practice_state_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='state',
        ),
    ]
